// web/src/components/ProductCard.vue
<script setup>
/**
 * 大图卡片。骨架是：图 → 名称 → 价格行 → 标尺 / 状态行 → chips。
 *
 * 两家的卡片是**同一个骨架**，但信息层级和几何都不一样，所以每一处差异都挂一个
 * `META.features` 开关，组件里没有一处站点判断：
 *
 *   stickerTags   商品图上的角标（迪卡侬的 尾货/新品）
 *   brandMark     名称前那块品牌小字（迪卡侬）
 *   priceOffBadge 价格行里的黄底 `降 N 元` 角标（迪卡侬）。优衣库把降幅挪到了
 *                 下面那根比例条的条尾（红字）
 *   dealBarNumber 比例条尾部的红色降幅数字（优衣库）。同一件事不说两遍
 *   cardChips     卡片底部的 chips 行。**没有标签也照样留着**：它的 `margin-top: auto`
 *                 + `min-height` 托住卡片底边，整排卡片的底对齐才不会被带歪
 *
 * 几何（图片比例、网格列宽、卡片要不要 padding、名称怎么截断）全部在 styles.css 的
 * `[data-site=…]` 作用域里，这一层只管结构。
 *
 * 2026-10-06 从 React 翻成 Vue，有三处值得记：
 *   · 原来在函数体里算的一串常量（sizeLine / now / was / cut / gone / text / delay）
 *     → computed。**必须**是 computed 而不是普通 const：它们依赖 props，
 *     props 一变就得跟着重算（React 那边每次渲染都会重跑函数体，天然如此）。
 *   · 那段 `{gone ? … : rate > 0 ? (dealBarNumber ? A : B) : C}` 的三层嵌套三元
 *     → v-if / v-else-if / v-else。**拆平之后好读多了** —— 这不是为了迁就 Vue，
 *     是 Vue 逼着把它摊开，反而回到了它本来该有的样子。
 *   · `style={{ '--w': … }}` → `:style`，自定义属性照样能绑。
 */
import { computed } from 'vue';
import { chips, goneNote, num, priceParts, tagLabel } from '../lib/format.js';
import { META } from '../lib/site.js';
import CardActions from './CardActions.vue';
import CardPicture from './CardPicture.vue';

/**
 * 这一行最多列几档尺码，超了就只写「剩 N 档」。
 *
 * 尺码改成 kbd 方块之后重量的（1440 宽时那行可用 322px）：方块比「 · 」分隔宽，
 * 能排一行的上限跟着降——童装厘米码只到 5 档，腰围厘米码到 6 档、字母码到 8 档。
 * 取最保守的 5。再多就折成第二行，一折就把同一行卡片的价格线顶歪。
 */
const MAX_SIZE_LABELS = 5;

const props = defineProps({
  deal: { type: Object, required: true },
  index: { type: Number, default: 0 },
  onPick: { type: Function, default: null },
  onHide: { type: Function, default: null },
});

const feats = META.features;

/**
 * 图片左下角那块「剩下哪些尺码」（2026-10-01 起压在图上，不再占名字那一行）：
 *   码全 / 没有尺码信息 → 不显示
 *   断码                → 显示剩下哪些尺码
 *   **全是 cm 的量体尺码 → 不显示**：优衣库那批「53cm / 58cm」压在图上很难看
 *                        （用户 2026-10-01：「遇到 cm 的断码的，就别显示了，很难看」）。
 *   混着的时候只去掉 cm 那几个，正常的 S / M / L 照旧显示。
 */
const sizeLine = computed(() => {
  const allLabels = props.deal.sizes?.labels ?? [];
  const labels = allLabels.filter((l) => !/cm/i.test(String(l)));
  const sizes = props.deal.sizes;
  if (!sizes || sizes.full) return null;
  if (allLabels.length > 0 && labels.length === 0) return null; // 全是 cm：整条不显示
  if (labels.length > MAX_SIZE_LABELS) return { lead: '', text: `剩 ${sizes.count} 档`, plain: `剩 ${sizes.count} 档` };
  if (labels.length) return { lead: '剩余：', labels, plain: labels.join(' · ') };
  return { lead: '', text: `剩 ${sizes.count} 档`, plain: `剩 ${sizes.count} 档` };
});

// 动效错开只给前几行，否则滚到下面时动画早跑完了
const delay = computed(() => Math.min(props.index, 11) * 40);
const now = computed(() => priceParts(props.deal.price));
const was = computed(() => priceParts(props.deal.launchPrice));
const cut = computed(() => props.deal.launchPrice > props.deal.price);
// 连续两轮没在抓取池里见到（只有手动 track 的商品会带着这个标记进来，见 db.mjs 的 missed）
const gone = computed(() => props.deal.gone === true);
const text = computed(() => chips(props.deal.tags));
const barStyle = computed(() => ({ '--w': `${Math.min(1, props.deal.rate) * 100}%`, animationDelay: `${delay.value}ms` }));

// 名字**原样显示**，不再按斜杠截断。
//
// 2026-10-06 用户：「商品名，写成和官网一样的，比如
// 男装/男女同款 UT Disney x F1®印花T恤/短袖T恤 488131，这种……现在用户反馈说要全的」。
// 这里原先写的是 `name.split('/')[0]`（只留斜杠前面那半段）。现在照原样渲染；
// 长出去的部分由 CSS 的省略号兜着，`title` / `aria-label` 里始终是全名。
</script>

<template>
  <article class="card" role="listitem">
    <!-- 角标只有在 stickerTags 打开时才需要一个定位父盒（迪卡侬），
         否则就保持「一个光秃秃的 .picframe」——多包一层会让原本挂在
         .picframe 上的对齐规则失效。
         图片那一块本身抽成了 CardPicture：两种外壳要渲染同样的内容，
         而模板不能像 React 那样用一个变量把渲染结果共用出去。 -->
    <div v-if="feats.stickerTags" class="card__picwrap">
      <CardPicture :image="props.deal.image" :url="props.deal.url" :size-line="sizeLine" />
      <!-- 角标贴在图上：红＝尾货清仓、灰＝新品 -->
      <span v-for="t in text" :key="t" class="tagbox" :class="`tagbox--${t}`">{{ tagLabel(t) }}</span>
    </div>
    <CardPicture v-else :image="props.deal.image" :url="props.deal.url" :size-line="sizeLine" />

    <!-- 名称那一行：**整行是链接**（两行截断由 CSS 兜住） -->
    <a
      class="card__name"
      :href="props.deal.url"
      target="_blank"
      rel="noreferrer"
      :title="props.deal.name"
      :aria-label="sizeLine ? `${props.deal.name}　${sizeLine.lead}${sizeLine.plain}` : props.deal.name"
    >
      {{ props.deal.name }}
    </a>

    <!-- 价格三件套，右端跟着收藏 / 不再出现两个动作 -->
    <div class="card__prices">
      <span class="card__now n" :class="{ 'card__now--flat': !(props.deal.rate > 0 && !gone) }">
        <span class="now__sym">{{ now.sym }}</span>
        <span class="now__int">{{ now.int }}</span>
        <span class="now__dec">{{ now.dec }}</span>
      </span>
      <!-- 迪卡侬：官网把折扣写成「6.0折」，这里写降幅，和榜单、排序的口径一致 -->
      <span v-if="feats.priceOffBadge && props.deal.rate > 0 && !gone" class="offbadge n">
        降 {{ num(Math.round(props.deal.saving)) }} 元
      </span>
      <span v-if="cut" class="card__was n">{{ was.sym }}{{ was.int }}{{ was.dec }}</span>
      <CardActions :watched="props.deal.tracked" :on-pick="props.onPick" :on-hide="props.onHide" />
    </div>

    <div v-if="gone" class="card__deal card__deal--flat" :class="{ 'card__deal': feats.dealBarNumber }">
      {{ goneNote(props.deal.lastSeenAt) }}
    </div>
    <!-- 优衣库：比例条和降幅红字同行，红字贴在条尾，条占满剩余宽度。
         直接说「降 190 元」——省下的钱是实打实的数，百分比还得自己换算 -->
    <div v-else-if="props.deal.rate > 0 && feats.dealBarNumber" class="card__deal">
      <span class="card__bar" aria-hidden="true"><i :style="barStyle" /></span>
      <span class="card__off n">降 {{ num(Math.round(props.deal.saving)) }} 元</span>
    </div>
    <!-- 迪卡侬：只有一根条，长度同样等于降幅 -->
    <span v-else-if="props.deal.rate > 0" class="card__bar" aria-hidden="true"><i :style="barStyle" /></span>
    <div v-else class="card__deal--flat" :class="{ 'card__deal': feats.dealBarNumber }">尚未降价，正在替你盯着</div>

    <!-- 这一行现在只剩「待拔草」标签；没有标签也照样留着，托住卡片底边 -->
    <div v-if="feats.cardChips" class="card__chips">
      <span v-if="feats.trackChip && props.deal.tracked" class="chip chip--tracked">★ 待拔草</span>
    </div>
  </article>
</template>

// web/src/components/ProductCard.jsx
import { chips, goneNote, num, priceParts, tagLabel } from '../lib/format.js';
import { META } from '../lib/site.js';
import { CardActions } from './CardActions.jsx';

/**
 * 大图卡片。两家的卡片是**同一个骨架**（图 → 名称 → 价格行 → 标尺 / 状态行 → chips），
 * 但信息层级和几何都不一样，所以下面每一处差异都挂一个 `META.features` 开关，
 * 组件里没有一处站点判断：
 *
 *   stickerTags   商品图上的角标（迪卡侬的 尾货/新品）。优衣库那份没有：
 *                 它的促销类型全在工具条页签里，图上再挂一个红角标只是噪音
 *   brandMark     名称前那块品牌小字（迪卡侬）。优衣库的名称里没有品牌
 *   priceOffBadge 价格行里的黄底 `-xx%` 角标（迪卡侬）。优衣库把降幅挪到了
 *                 下面那根比例条的条尾（红字），价格行只留价格和动作
 *   dealBarNumber 比例条尾部的红色降幅数字（优衣库）。迪卡侬只在条上画长度、
 *                 数字在价格行的黄角标里，同一件事不说两遍
 *   cardChips     卡片底部的 chips 行（迪卡侬）。**没有标签也照样留着**：
 *                 它的 `margin-top: auto` + `min-height` 托住卡片底边，
 *                 整排卡片的底对齐才不会被「有没有标签、有没有收藏」带歪
 *
 * 几何（图片比例 3:4 / 1:1、网格 auto-fill 258px / 固定 4 列且列间距 0、
 * 卡片要不要 padding、名称两行怎么截断）全部在 styles.css 的
 * `[data-site=…]` 作用域里，这一层只管结构。
 *
 * 一处和官网不同，两家都适用：官网卡片**不显示原价**（原价只在商品页出现），
 * 但这页的全部意义就是上市价对比，所以把上市价补在现价后面 —— 灰字、划删除线。
 * 划线只在真降了的时候才画（`cut`），没降的原价等于现价，划它没意义。
 */
/**
 * 这一行最多列几档尺码，超了就只写「剩 N 档」。
 *
 * 尺码改成 kbd 方块之后重量的（1440 宽时那行可用 322px）：方块比「 · 」分隔宽，
 * 能排一行的上限跟着降——童装厘米码（110cm 这种）只到 **5** 档，腰围厘米码到 6 档、
 * 字母码到 8 档。取最保守的 5。再多就折成第二行，一折就把同一行卡片的价格线顶歪。
 */
const MAX_SIZE_LABELS = 5;

export function ProductCard({ deal, index, onPick, onHide }) {
  const { url, image, name, brand, tags, tracked, rate, saving, sizes } = deal;

  /**
   * 图片左下角那块「剩下哪些尺码」（2026-10-01 起压在图上，不再占名字那一行）：
   *   码全 / 没有尺码信息 → 不显示
   *   断码                → 显示剩下哪些尺码（图片已经看得够清楚，这时真正决定买不买的是
   *                         「我的码还在不在」）
   *   **全是 cm 的量体尺码 → 不显示**：优衣库有一批用「53cm / 58cm」这种身长尺码，
   *   压在商品图上很难看（用户 2026-10-01：「遇到 cm 的断码的，就别显示了，很难看」）。
   *   混着的时候只去掉 cm 那几个，正常的 S / M / L 照旧显示。
   *
   * 尺码是适配器算好的（见 src/sites/uniqlo.mjs 的 sizeInfo）：接口给的是**有货的
   * 内部码**，翻译成人话才到这儿。商品名不受影响 —— 它在上面一行，完整名字在 title 里。
   */
  const allLabels = sizes?.labels ?? [];
  const sizeLabels = allLabels.filter((l) => !/cm/i.test(String(l)));
  const sizeLine =
    !sizes || sizes.full
      ? null
      : allLabels.length > 0 && sizeLabels.length === 0
        ? null // 全是 cm：整条不显示
        : sizeLabels.length > MAX_SIZE_LABELS
          ? { lead: '', text: `剩 ${sizes.count} 档`, plain: `剩 ${sizes.count} 档` } // 太长，只报个数（不拆方块）
          : sizeLabels.length
            ? { lead: '剩余：', labels: sizeLabels, plain: sizeLabels.join(' · ') } // 一档一个 kbd 小方块
            : { lead: '', text: `剩 ${sizes.count} 档`, plain: `剩 ${sizes.count} 档` };
  // 动效错开只给前几行，否则滚到下面时动画早跑完了
  const delay = Math.min(index, 11) * 40;
  const now = priceParts(deal.price);
  const was = priceParts(deal.launchPrice);
  const cut = deal.launchPrice > deal.price;
  // 连续两轮没在抓取池里见到（只有手动 track 的商品会带着这个标记进来，见 db.mjs 的 missed）
  const gone = deal.gone === true;
  const feats = META.features;
  const text = chips(tags);

  // 名字**原样显示**，不再按斜杠截断。
  //
  // 2026-10-06 用户：「商品名，写成和官网一样的，比如
  // 男装/男女同款 UT Disney x F1®印花T恤/短袖T恤 488131，这种……现在用户反馈说要全的」。
  // 这里原先写的是 `name.split('/')[0]`（只留斜杠前面那半段）。它和数据侧那版
  // 「name 存 name4zhCN」叠在一起，用户实际看到的就只剩「UT Disney x F1®印花T恤」。
  // 现在数据侧给的是官网完整标题（含人群前缀与货号），这里也照原样渲染；
  // 长出去的部分由 CSS 的省略号兜着，`title` / `aria-label` 里始终是全名。

  /** 图片那一块。角标只有在 stickerTags 打开时才需要一个定位父盒（迪卡侬），
   *  否则优衣库那边就保持「一个光秃秃的 .picframe」——多包一层会让原本
   *  挂在 .picframe 上的对齐规则失效 */
  const pic = image ? (
    <div className="picframe">
      <a className="piclink" href={url} target="_blank" rel="noreferrer">
        {/* 不写 width/height 属性：属性会变成 used height 把 aspect-ratio 顶掉，
            图就被塞进一个非本比例的框里留白。比例靠 CSS 的 aspect-ratio 定
            （优衣库 3:4、迪卡侬 1:1），所以这里只给 src */}
        <img
          className="card__img"
          src={image}
          /* 卡片约 175 CSS px，2x 屏需要 350 —— 400 那档正好够，体积只有 561 的四分之一。
             没有 srcset 时，手机首屏十几张图全是 1200px 的源图，约 700 KB。 */
          srcSet={image.replace('@561.', '@400.') + ' 400w, ' + image + ' 561w'}
          sizes="(max-width: 760px) 45vw, 200px"
          alt=""
          loading="lazy"
          decoding="async"
        />
      </a>
          {/* 断码的剩余尺码压在**图片左下角**（用户 2026-10-01：「弄到图片左下角，和图片重叠在一起，
              不要占标题的位置」）。它排在 <a> 外面，不改变链接的点击范围；
              CSS 里再补 pointer-events: none，点它等于点图片。 */}
          {sizeLine && (
            // 「剩余」这两个字不显示（用户 2026-10-01：「删掉剩余两个字，感觉影响美观」）；
            // 它仍留在 aria-label 里，读屏听到的是「商品名　剩余：S M L」。
            <span className="card__sizes">
              {/* 每一档包一个 <kbd>：方形、细边、浅底，像键盘键帽。
                  语义上 <kbd> 本来是「用户输入」，这里纯粹借它的方块外观——
                  它没有 ARIA role，读屏不会多念什么。 */}
              {sizeLine.labels
                ? sizeLine.labels.map((l) => (
                    <kbd className="sizekey" key={l}>
                      {l}
                    </kbd>
                  ))
                : <span className="cardsizes__list">{sizeLine.text}</span>}
            </span>
          )}
    </div>
  ) : (
    /* 兜底，正常情况下用不到：payload 里不会有没图的商品（生成时就剔掉了，见
       core/report.mjs 的 buildPayload）。留着是因为「少一张图」比「一张破图」好看，
       万一哪天有别的路径塞进来一件没图的，页面也不至于难看 */
    <span className="card__img card__img--none" />
  );

  return (
    <article className="card" role="listitem">
      {feats.stickerTags ? (
        <div className="card__picwrap">
          {pic}
          {/* 角标贴在图上：位置照迪卡侬官网 `.tag-box absolute left-10`。
              官网用它写「特惠产品」（人人都有），这里改写成我们自己的两个信号——
              红＝尾货清仓、灰＝新品。中文译本来自 meta.tagLabels，
              `discount_zone` 因为「全都命中等于没有标签」不进 chipTags */}
          {text.map((t) => (
            <span key={t} className={`tagbox tagbox--${t}`}>
              {tagLabel(t)}
            </span>
          ))}
        </div>
      ) : (
        pic
      )}

      {/* 名称那一行：**整行是链接**（两行截断由 CSS 兜住）。
          断码时这一行显示剩下的尺码、不显示名字——名字留给 title / aria-label
          （鼠标停一下就能看到，读屏也读得到）。

          ⚠️ 这里原本是「品牌内联 / 整行链接」两套分支，用 feats.brandMark 二选一。
          两站的 brandMark 都是 false，那一支是死代码，却让「尾货」标记被我插错两次
          （一次插进没用到的分支，一次用 includes('card__name') 定位又落回它）。
          2026-10-01 直接删掉合成一份：要恢复就去 git 里找。 */}
      <a
        className="card__name"
        href={url}
        target="_blank"
        rel="noreferrer"
        title={name}
        aria-label={sizeLine ? `${name}　${sizeLine.lead}${sizeLine.plain}` : name}
      >
        {/* 名称**永远显示**（原来断码时会被尺码顶掉，优衣库有 26% 的卡片因此没有名字），
            显示的就是官网完整标题，断码时把剩余尺码跟在名称后面。 */}
        {name}
      </a>

      {/* 价格三件套，右端跟着收藏 / 不再出现两个动作——动作挨着价格，
          不用单独再占一行，卡片下半截也就少一层 */}
      <div className="card__prices">
        <span className={`card__now n${rate > 0 && !gone ? '' : ' card__now--flat'}`}>
          <span className="now__sym">{now.sym}</span>
          <span className="now__int">{now.int}</span>
          <span className="now__dec">{now.dec}</span>
        </span>
        {/* 迪卡侬：官网把折扣写成「6.0折」，这里写降幅，和榜单、排序的口径一致 */}
        {feats.priceOffBadge && rate > 0 && !gone && (
          <span className="offbadge n">降 {num(Math.round(saving))} 元</span>
        )}
        {cut && (
          <span className="card__was n">
            {was.sym}
            {was.int}
            {was.dec}
          </span>
        )}
        <CardActions watched={tracked} onPick={onPick} onHide={onHide} />
      </div>

      {gone ? (
        <div className={feats.dealBarNumber ? 'card__deal card__deal--flat' : 'card__deal--flat'}>
          {goneNote(deal.lastSeenAt)}
        </div>
      ) : rate > 0 ? (
        META.features.dealBarNumber ? (
          /* 优衣库：比例条和降幅红字同行，红字贴在条尾，条占满剩余宽度 */
          <div className="card__deal">
            <span className="card__bar" aria-hidden="true">
              <i style={{ '--w': `${Math.min(1, rate) * 100}%`, animationDelay: `${delay}ms` }} />
            </span>
            {/* 直接说「降 190 元」（用户 2026-10-01：「百分数直接改成降 39 元这种，让人更明显的
                看清楚降了多少钱，百分比直觉不明」）。省下的钱是实打实的数，
                百分比还得自己换算。千分位走 num()，大额价格也读得清。 */}
            <span className="card__off n">降 {num(Math.round(saving))} 元</span>
          </div>
        ) : (
          /* 迪卡侬：只有一根条，长度同样等于降幅（数字在价格行的黄角标里） */
          <span className="card__bar" aria-hidden="true">
            <i style={{ '--w': `${Math.min(1, rate) * 100}%`, animationDelay: `${delay}ms` }} />
          </span>
        )
      ) : (
        <div className={feats.dealBarNumber ? 'card__deal card__deal--flat' : 'card__deal--flat'}>
          尚未降价，正在替你盯着
        </div>
      )}

      {feats.cardChips && (
        /* 收藏 / 不再出现已经挪到价格行，这一行现在只剩「待拔草」标签。
           没有标签也照样留着：min-height 托住卡片底边，整排卡片的底对齐才不会被
           有没有标签、有没有收藏带歪 */
        <div className="card__chips">
          {feats.trackChip && tracked && <span className="chip chip--tracked">★ 待拔草</span>}
        </div>
      )}
    </article>
  );
}
